### ISSUE TITLE
README needed

### ISSUE THREAD

**Issue by hexmode** [davidbarratt/mediawiki#1]
Could you create a README so that we can get an idea of how to use this and duplicate your work from the hackathon?

**Comment by davidbarratt** [comment]
hmm, I'm not sure if a README should be added to this repo. This repo is basically a boilerplate, so people using it would have to delete the README. :/ but perhaps after the patch on https://phabricator.wikimedia.org/T166956 is merged, documentation can be added to www.mediawiki.org.

If you really think a README _should_ be added, please leave a comment on the patch:
https://gerrit.wikimedia.org/r/c/mediawiki/composer/project/+/434764
